version: "3.9"

services:

  redis:
    image: "redis:alpine"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

  analyzer:
    image: "rgrun/music-analyzer"

    devices:
      - "/dev/snd:/dev/snd"

    command: python3 analyzer.py


  animation:
    image: "rgrun/music-animation"

    command: python3 animationmanager.py


# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

    