version: "3.9"

services:

  redis:
    image: "redis:alpine"

    container_name: music-cache

    command: redis-server /usr/local/etc/redis/redis.conf

    ports:
      - "6379:6379"

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

  analyzer:
    image: "rgrun/music-analyzer-raspberrypi"

    container_name: music-analyzer

    volumes:
      - ./recording/recordings:/essentia/recordings:ro

    links:
      - "redis"

    tty: true
    stdin_open: true

    # command: python3 analyzer.py

    networks:
      node_net:
        ipv4_address: 172.28.1.5


  animation:
    image: "rgrun/music-visualizer-raspberrypi"

    container_name: music-animation

    privileged: true

    links:
      - "redis"

    tty: true
    stdin_open: true


    # command: python3 animationmanager.py

    networks:
      node_net:
        ipv4_address: 172.28.1.6


# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

    